### ISSUE TITLE
您好，我想请问一下ot_run.py里几个参数的含义

### ISSUE THREAD

**Issue by q178** [Jingjing-NLP/VOLT#1]
source_file 
    target_file 
    token_candidate_file 
    vocab_file 
    max_number 
    interval 

以及他训练出来的是单独的词表还是共享的词表？

**Comment by Jingjing-NLP** [comment]
ot_run的使用说明增加到了readme中，您可以去readme查看更多细节。单独的词表还是共享的词表目前的版本是取决于用户的输入。用户可以选择根据共享语料学习词表还是根据不同的语料学习不同的词表～

**Comment by Jingjing-NLP** [comment]
The descriptions of ot_run have been included in README.md. I temporarily close this issue.
