### ISSUE TITLE
Confused about subword-nmt style output

### ISSUE THREAD

**Issue by bbo0924** [Jingjing-NLP/VOLT#15]
![volt_problem](https://user-images.githubusercontent.com/28530189/129704026-b73b68f4-846e-49dd-ba4a-38ce69d0c18b.PNG)
Hi! I am confused about why both source file and target file are put into same bpeoutput/source.file after bpe processing?

**Comment by Jingjing-NLP** [comment]
Thanks for pointing out this typo! I have fixed it in the latest version. It should be:
```
python3 subword-nmt/apply_bpe.py -c $BPE_CODE < source_file > bpeoutput/source.file
python3 subword-nmt/apply_bpe.py -c $BPE_CODE < target_file > bpeoutput/target.file 
```
