### ISSUE TITLE
run_ot and run_ot_write

### ISSUE THREAD

**Issue by kirefu** [Jingjing-NLP/VOLT#17]
Hi there,

I am trying to reconcile your code with the description in Algorithm 1 of your paper.

In the paper:

entropy, vocab = get_vocab(optimal matrix)
vocabularies.append(entropy,vocab)
Output v∗ from vocabularies satisfying Eq. 3

https://github.com/Jingjing-NLP/VOLT/blob/c9f2e692b2a25ba6be19d067020d0eeaa288ce55/ot_run.py#L141

However, in the code for run_ot, the transport matrix or a vocabulary set for each timestep t is not stored, only the (vocab_size, entropy) pairs are.

Then run_ot_write() takes this optimal vocab size, and recalculates the transport matrix again, and I don't see how this is different from when it was calculated in the for loop with run_ot, surely the same matrix is outputted? I also don't understand how run_ot_write() is doing the same thing as "Output v∗ from vocabularies satisfying Eq. 3" from Algorithm 1, as there are no vocabs being taken into consideration.

Would be very grateful if you could help clarify the above, as I am keen to implement your work :)

**Comment by Jingjing-NLP** [comment]
Yes, your understanding is right!  There are two argmax operations here. The outer argmax means the maximum value over all timesteps.

**Comment by kirefu** [comment]
Thanks!
