### ISSUE TITLE
How can I use SentencePiece to generate vocb

### ISSUE THREAD

**Issue by andongBlue** [Jingjing-NLP/VOLT#18]

**Comment by andongBlue** [comment]
I followed the step about building the environment. I found that I cannot use sentencepiece too.  `spm/spm_train.py`.
I used `pip3 install sentencepiece`. The step can not generate spm file.

How can use sentencepiece to generate vocb to follow next step?

**Comment by Jingjing-NLP** [comment]
This channel has not new comments.  I temporarily close this issue.
