### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by q178** [Jingjing-NLP/VOLT#2]
Traceback (most recent call last):
  File "ot_run.py", line 174, in <module>
    optimal_size = run_ot(oldtokens, chars, int(max_number),int(interval))
  File "ot_run.py", line 126, in run_ot
    Gs,_ = ot.sinkhorn(a,b,d_matrix,1.0,method='sinkhorn',numItermax=400)
ValueError: too many values to unpack (expected 2)

**Comment by 9173860** [comment]
You should install POT using the local one which the author made changes in `ot.bregman.sinkhorn`

**Comment by q178** [comment]
python setup.py install  
然后出现Microsoft Visual C++ 14.0 is required.
但是我已经安装了visual studio2015
是我执行错了吗？

**Comment by Jingjing-NLP** [comment]
You can try the following commands:

```
cd ../POT
python3 -m pip install --force-reinstall --editable ./ -i https://pypi.doubanio.com/simple --user
```

**Comment by q178** [comment]
十分感谢您的回复，虽然我在自己电脑上仍缺vc++14.0，但在同学电脑上已经成功复现，十分感谢您的解惑！

**Comment by Jingjing-NLP** [comment]
嗯嗯是可以的，可以具体参考examples目录下的TED bilingual translation脚本～

**Comment by Jingjing-NLP** [comment]
Since the POT issue has been solved, I temporarily close this issue.
