### ISSUE TITLE
Scripts for MUV-search

### ISSUE THREAD

**Issue by Saltychtao** [Jingjing-NLP/VOLT#21]
Hello,   I am trying to use the MUV-search method mentioned in your paper to find an optimal vocabulary size. As is shown in Table 4, the optimal vocabulary size is 9.7k. However, when I am trying to reproduce the results, I find that MUV values are decreasing monotonously with the vocab size, therefore the max MUV value always belongs to the minimal vocab size.

Below are the vocab size, entropy value, and MUV values calculated on the WMT14 En-De dataset:

 | BPE vocab size | Entropy |          MUV |
 |           4117         |    5.62    |            -      |
 |           5043         |    4.32 | 1.4038877e-3 |
 |           5976         |    3.62 | 7.5026795e-4 |
 |           6885         |     3.20 | 4.6204620e-4 |
 |           7783         |    2.94 | 2.8953229e-4 |
 |           8645         |    2.76 | 2.0881671e-4 |
 |           9504         |    2.64 | 1.3969732e-4 |
 |          10348        |    2.54 | 1.1848341e-4 |
 |          11173        |    2.46 | 9.6969697e-5 |
 |          11977        |    2.39 | 8.7064677e-5 |
 |          19909        |   2.081 | 3.8956127e-5 |

Can you pleases provide the source code for MUV search or just point out where the error might happen?

**Comment by Jingjing-NLP** [comment]
Hi, I have no idea how you calculate MUV scores. To address your problem,  I have uploaded one example to calculate MUV scores for WMT14 En-De. You can find the running script on examples/muv-search.sh.
 
You can run this script and this script will show that BPE-6K is the vocabulary with the highest MUV score.

**Comment by Saltychtao** [comment]
Thank you for your response! The problem has been solved now, the error is caused by a misunderstanding of the average token length.
