### ISSUE TITLE
标点符号的问题

### ISSUE THREAD

**Issue by andongBlue** [Jingjing-NLP/VOLT#22]
您好，
我先用sentencepiece生成了一个词表，里边的标点符号既有单个的标点(如：。/，/！/？等)，也有连续的标点(如：？？？/ 。。。/！！！)。通过VOLT算法生成的新词表中，我观察到词表中没有了单个的标点，只有连续的标点。并且VOLT生成的标点既不是中文的标点也不是英文的标点。

请问在标点处理这边，您是怎么处理的呢？

**Comment by Jingjing-NLP** [comment]
您好，VOLT程序没有对标点的特殊处理。

VOLT生成的词表全部来源于初始化的词表候选。volt生成的词表相当于merge action，如果词表里有这个单词，就会合并。因此如果volt词表里没有单个标点符号，也不会被识别成unk，而是单独的字符。

希望可以解答您的问题～
