### ISSUE TITLE
--vocab_file

### ISSUE THREAD

**Issue by a1385775** [Jingjing-NLP/VOLT#5]
Hello 
About the parameter: --vocab_file
If the vocabularies of the two languages are separately trained, how to set it up

**Comment by Jingjing-NLP** [comment]
Hi

You can run the VOLT on two languages respectively. Here is an example:

```
#For non-seq2seq tasks with one source file, you can use the following commands:
#subword-nmt style
python3 ../ot_run.py --source_file bpeoutput/source.file \
          --token_candidate_file $BPE_CODE \
          --vocab_file bpeoutput/vocab --max_number 10000 --interval 1000  --loop_in_ot 500 --tokenizer subword-nmt --size_file bpeoutput/size 
  
#sentencepiece style
BPE_CODE=spm.vocab
python3 ../ot_run.py --source_file spmoutput/source.file \
          --token_candidate_file spm.vocab  \
          --vocab_file spmoutput/vocab --max_number 10000 --interval 1000  --loop_in_ot 500 --tokenizer sentencepiece --size_file spmoutput/size 
```

**Comment by a1385775** [comment]
Thank you very much for your reply！

My training language is ZH-EN（Chinese-English）, which is not applicable to the shared-vocab called “**learn_joint_bpe_and_vocab**”. But I guess your work, **“cat source_file > training_data cattarget_file >> training_data”**, is similar to that shared vacab, right? So, what can I do with ZH-EN language in that case?

I usually use this：
```
python spm_train.py -i en.tok -o spm_en
python spm_train.py -i zh.tok -o spm_zh

python $spmencode/spm_encode_mp.py --model spm_zh.model --inputs zh.tok --outputs train.zh
python $spmencode/spm_encode_mp.py --model spm_en.model --inputs en.tok --outputs train.en
```

**Comment by a1385775** [comment]
> Hi
> 
> You can run the VOLT on two languages respectively. Here is an example:
> 
> ```
> #For non-seq2seq tasks with one source file, you can use the following commands:
> #subword-nmt style
> python3 ../ot_run.py --source_file bpeoutput/source.file \
>           --token_candidate_file $BPE_CODE \
>           --vocab_file bpeoutput/vocab --max_number 10000 --interval 1000  --loop_in_ot 500 --tokenizer subword-nmt --size_file bpeoutput/size 
>   
> #sentencepiece style
> BPE_CODE=spm.vocab
> python3 ../ot_run.py --source_file spmoutput/source.file \
>           --token_candidate_file spm.vocab  \
>           --vocab_file spmoutput/vocab --max_number 10000 --interval 1000  --loop_in_ot 500 --tokenizer sentencepiece --size_file spmoutput/size 
> ```

`python3 ../ot_run.py --source_file rawspm/train.en.spm   --token_candidate_file spm.en.vocab            --vocab_file vocab3  --max_number 30000 --interval 1000  --loop_in_ot 500 --tokenizer sentencepiece --size_file enzh.size`

But
```
Traceback (most recent call last):
  File "../ot_run.py", line 207, in <module>
    oldtokens = get_tokens.get_tokens(source_file, target_file, token_candidate_file, tokenizer=args.tokenizer) # get token candidates and their frequencies
  File "/DATA2/disk1/huangjihao/ACL/VOLT/get_tokens.py", line 86, in get_tokens
    tokens = read_tokens(target_file, tokens=tokens, tokenizer=tokenizer)
  File "/DATA2/disk1/huangjihao/ACL/VOLT/get_tokens.py", line 18, in read_tokens
    with open(path, 'r') as sr:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
