### ISSUE TITLE
Are there any recommended hyperparameters for a larger dataset?

### ISSUE THREAD

**Issue by SefaZeng** [Jingjing-NLP/VOLT#7]
I try to use VOLT for a larger dataset like 100 million and it decrease the bpe file from 32000 to 6000. But the new bpe codes_file brings absolutely performance degradation in BLEU, like 35->19. 
Are there any parameters I need to change for a larger dataset?

**Comment by Jingjing-NLP** [comment]
Hi, we have conduct experiments on En-Fr experiments with around 40M datasets and do not observe the performance decay. For other datasets, we do not observe such performance reduction. I am also very confused to see this results.  Would you like to provide more implementation details? Thanks!

**Comment by SefaZeng** [comment]
> Hi, we have conduct experiments on En-Fr experiments with around 40M pairs and do not observe the performance decay. For other datasets, we still do not observe such performance reduction. I am also very confused to see this results. Would you like to provide more implementation details? Thanks!

Sorry, I used the wrong bpe file when I was testing the VOLT performance. By using the right bpe file, volt absolutely decrease the vocab size with slightly performance loss. Thank you for your response and such a great work!

**Comment by Jingjing-NLP** [comment]
> > Hi, we have conduct experiments on En-Fr experiments with around 40M pairs and do not observe the performance decay. For other datasets, we still do not observe such performance reduction. I am also very confused to see this results. Would you like to provide more implementation details? Thanks!
> 
> Sorry, I used the wrong bpe file when I was testing the VOLT performance. By using the right bpe file, volt absolutely decrease the vocab size with slightly performance loss. Thank you for your response and such a great work!

Thanks for your comments!  Since we set the default settings according to experiments on datasets up to 40M pairs, it is ok to try larger --max_number and --interval for a larger dataset. We will test VOLT on larger datasets. If you have any other quesitons, please feel free to let us know.
