### ISSUE TITLE
Missing `ted/onemanydata` data?

### ISSUE THREAD

**Issue by tiendung** [Jingjing-NLP/VOLT#8]
[run_ted_bilingual_onetomany.sh](https://github.com/Jingjing-NLP/VOLT/blob/master/examples/run_ted_bilingual_onetomany.sh) script using data from `ted/onemanydata` but I cannot find it in the link you provided at the end of `README.md` https://drive.google.com/drive/folders/1FNH7cXFYWWnUdH2LyUFFRYmaWYJJveKy

And, i'm curious to know what is the purpose`ted/onemanydata` experiment?

**Comment by Jingjing-NLP** [comment]
Hi, the one-to-many data is uploaded to https://drive.google.com/drive/u/1/folders/1du13KQG6JM9u1JLhnS47Pu4BQtfP2AK3 .
